  - name: including vars from crypt.yml
    include_vars: /etc/ansible/roles/InstallAndConfigurePostgres/crypt.yml

  - name: Exclude postgres from default CentOS repositories
    lineinfile:
      path: "/etc/yum.repos.d/CentOS-Base.repo"
      line: exclude=postgresql*
      insertafter: "^baseurl"

  - name: Installing official PostgreSQL repository
    shell:  yes 'y' | yum install https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm

  - name: Installing psycopg
    shell: pip install psycopg2==2.7.5 --ignore-installed
  
  - name: Install PostgreSQL server
    yum:
            name: postgresql11-server
            state: present

