  - name: Adding Kerberos Principals
    shell: |
            { echo "{{ password }}"; echo "{{ password }}"; } | kadmin.local -q "addprinc {{ user_name }}@{{ realm_name_in_uppercase }}"
            { echo "{{ password }}"; echo "{{ password }}"; } | kadmin.local -q "addprinc root/admin"
            kadmin.local -q "xst -norandkey -k /etc/security/keytabs/{{ user_name }}.keytab {{ user_name }}@{{ realm_name_in_uppercase }}"
            chown {{ user_name }}:{{ user_name }} /etc/security/keytabs/{{ user_name }}.keytab
            #/usr/sbin/kadmin.local -q "addprinc -randkey host/{{ system_hostname_with_realm }}"
            #/usr/sbin/kadmin.local -q "ktadd host/{{ system_hostname_with_realm }}"

  - name: Start services
    service:
            name: "{{ item }}"
            state: started
    with_items:
            - krb5kdc
            - kadmin

