        - name: Installing Telegraf as a Service.
          win_shell: .\telegraf.exe --service install --config "C:\Program Files\telegraf\telegraf.conf"
          args:
                chdir: 'C:\Program Files\telegraf'

        - name: Testing Telegraf with the edited config file
          win_shell: .\telegraf.exe --config "C:\Program Files\telegraf\telegraf.conf" --test >> C:\Program Files\telegraf\telegrafTest.txt
          args:
                chdir: 'C:\Program Files\telegraf'

        - name: Start Telegraf
          win_shell: net start telegraf

        - name: Creating telegraf.d
          win_file:
                path: 'C:\Program Files\telegraf\telegraf.d'
                state: directory

        - name: Copy conf file for creating network health UI
          win_copy:
                src: /opt/ansible/examples/zd_defaults.conf
                dest: 'C:\Program Files\telegraf\telegraf.d\'

